mode = "classic"


content = "<a:HappyCloud:1365575487333859398> 𝐹𝓇𝑒𝑒 𝒞𝒽𝒶𝓅𝓉𝑒𝓇 <a:TurtleDance:1365253970435510293> {global_mention}\n<a:5037sweetpianoyay:1368138418487427102> **{title}** <:pink_unlock:1368266307824255026>"

[allowed_mentions]
parse = ["everyone", "users", "roles"]

[[embeds]]
title = "<a:sun_clouds:1517425608143933470>**{chapter}**"
url = "{link}"
description = "{chaptername}"
description_when = "chaptername"
timestamp = "{pub_date_iso}"
color = { key = "free_chapter", default = "FFF9BF" }

[embeds.author]
name = "{translator}˙ᵕ˙"
url = "{translator_url}"
url_when = "translator_url"

[embeds.thumbnail]
url = "{featured_image_url}"
url_when = "featured_image_url"

[embeds.footer]
text = "{host}"
icon_url = "{host_logo_url}"
icon_url_when = "host_logo_url"

[components]
[[components.action_rows]]
[[components.action_rows.buttons]]
style = "link"
label = "Read here"
url = "{link}"
