mode = "classic"

content = "<a:Crown:1365575414550106154> 𝒫𝓇𝑒𝓂𝒾𝓊𝓂 𝒞𝒽𝒶𝓅𝓉𝑒𝓇 <a:TurtleDance:1365253970435510293>\n<a:sweetpianohappy:1368136820965249034> **{title}** <:pink_lock:1368266294855733291>"

[allowed_mentions]
parse = ["everyone", "users", "roles"]

[[embeds]]
title = "<a:moonandstars:1365569468629123184>**{chapter}**"
url = "{link}"
description = "{chaptername}"
description_when = "chaptername"
timestamp = "{pub_date_iso}"
color = { key = "paid_chapter", default = "A87676" }

[embeds.author]
name = "{translator}˙ᵕ˙"
url = "{translator_url}"
url_when = "translator_url"

[embeds.thumbnail]
url = "{featured_image_url}"
url_when = "featured_image_url"

[embeds.footer]
text = "{host}"
icon_url = "{host_logo_url}"
icon_url_when = "host_logo_url"

[components]
[[components.action_rows]]
[[components.action_rows.buttons]]
style = "link"
label = "{button_label}"
emoji = "{button_emoji}"
emoji_when = "button_emoji"
url = "{link}"
