name: Check RSS & Send Chapters

concurrency:
  group: rss-to-discord-chapters
  cancel-in-progress: false

on:
  schedule:
    - cron: '0 15 * * *'     # daily 23:00 MYT (UTC+8)
  repository_dispatch:
    types: [trigger-discord-notify]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  chapters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install discord.py feedparser python-dateutil

      # FREE feed → Mistmint threads
      - name: Run Free Chapters Bot
        if: >
          github.event_name == 'schedule' ||
          github.event_name == 'workflow_dispatch' ||
          (github.event_name == 'repository_dispatch' && github.event.client_payload.feed == 'free')
        timeout-minutes: 5
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          # Per-novel thread IDs (add more as you create them; names must match short_code + "_THREAD_ID")
          TDLBKGC_THREAD_ID: ${{ secrets.TDLBKGC_THREAD_ID }}
          # BOOTSTRAP_LATEST: '1'   # uncomment for first run to avoid backfill
        run: python bot_free_chapters.py

      # PAID feed → Mistmint threads
      - name: Run Paid Chapters Bot
        if: >
          github.event_name == 'schedule' ||
          github.event_name == 'workflow_dispatch' ||
          (github.event_name == 'repository_dispatch' && github.event.client_payload.feed == 'paid')
        timeout-minutes: 5
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          # Mirror the same set here
          TDLBKGC_THREAD_ID: ${{ secrets.TDLBKGC_THREAD_ID }}
        run: python bot_paid_chapters.py

      - name: Sync & commit state_rss.json
        shell: bash
        run: |
          git pull --rebase --autostash
          git add state_rss.json
          if git diff --cached --quiet; then
            echo "No state changes to commit."
          else
            git -c user.name='github-actions[bot]' -c user.email='github-actions[bot]@users.noreply.github.com' commit -m "ci: update state_rss.json"
            git push
          fi
