name: Check RSS & Send Comments

on:
  schedule:
    - cron: '0 * * * *'
  repository_dispatch:
    types: [trigger-discord-comments]
  workflow_dispatch:

concurrency:
  group: rss‐to‐discord‐workflow
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  comments:
    concurrency:
      group: rss-to-discord-comments
      cancel-in-progress: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install feedparser python-dateutil aiohttp

      - name: Run Comments Bot
        timeout-minutes: 5
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_COMMENTS_CHANNEL: ${{ secrets.DISCORD_COMMENTS_CHANNEL }}
          PYTHONUNBUFFERED: 1
        run: python -u bot_comments.py

      - name: Commit updated state file
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main || true
          git add state_rss.json
          if git diff --cached --quiet; then
            echo "No state changes to commit."
          else
            git commit -m "ci: update state_rss.json"
            git push origin main
          fi
